sequenceDiagram
    Server->>Client: ask for password change
    Client->>Client: generate KEKek
    Client->>Client: encrypt KEK using server's public key
    Client->>Server: POST /kek
    Server->>Server: store KEK
    Server->>Client: OK
